### ISSUE TITLE
Needs Big-O time complexity in documentation.

### ISSUE THREAD

**Issue by RayfenWindspear** [fatih/set#30]
Without time complexity information for each Set method, it is difficult to determine whether or not to use this library. I thought about using this library, until I read the code for Intersect, which calls Union twice, which in turn calls Copy. The whole operation is hardly optimized. I DO understand that this library is for convenience purposes and I am NOT intending to bash your code, but if people are to rely on such libraries, they at least need to know the complexity of the operations.

To further make my point, I added a benchmark for a piece of code I wrote for the intersection of two sets, which I make no claim as being the fastest implementation, but the order is easily worked out as: 
O( (len(set1) + len(set2)) * O(map) )

(I took the liberty of interleaving the results for easier comparison.)

```
// Returns the intersection of two slices
func SimpleIntersection(l1 []int, l2 []int) []int { // O((len(l1) + len(l2)) * O(map))
	ret := []int{}
	m := make(map[int]bool, len(l1))

	for _, item := range l1 {
		m[item] = true
	}

	for _, item := range l2 {
		if m[item] == true {
			ret = append(ret, item)
		}
	}
	return ret
}
```

```
PASS
BenchmarkSetEquality-4              	   10000	    780659 ns/op
BenchmarkSubset-4                   	   10000	    801358 ns/op
BenchmarkIntersection10-4           	  100000	     13075 ns/op
BenchmarkSimpleIntersection10-4     	 2000000	       601 ns/op
BenchmarkIntersection100-4          	   10000	    118579 ns/op
BenchmarkSimpleIntersection100-4    	  200000	      6183 ns/op
BenchmarkIntersection1000-4         	    1000	   1302503 ns/op
BenchmarkSimpleIntersection1000-4   	   30000	     53364 ns/op
BenchmarkIntersection10000-4        	     100	  13888576 ns/op
BenchmarkSimpleIntersection10000-4  	    3000	    573658 ns/op
BenchmarkIntersection100000-4       	      10	 175577891 ns/op
BenchmarkSimpleIntersection100000-4 	     200	   7036305 ns/op
BenchmarkIntersection1000000-4      	       1	2828214630 ns/op
BenchmarkSimpleIntersection1000000-4	      10	 144838095 ns/op
ok  	github.com/fatih/set	41.404s
```

**Comment by RayfenWindspear** [comment]
I did some calculations just to check, and it appears that your Intersect does indeed have the same Big-O as mine, but has more overhead tied with the additional functionality. Mine stays about 13-20x faster, regardless of the value of N, so they experimentally have the same Big-O.

Anyway, the issue is not to compete, but to document the Big-O of the Set operations.

**Comment by sdboyer** [comment]
> but if people are to rely on such libraries, they at least need to know the complexity of the operations.

On the one hand, I'd argue it's optimistic to think that most working engineers today can make meaningful decisions based on Big O notation, let alone that they *need* to know it to rely on the library :) 

On the other, it certainly doesn't hurt to include it. I'd like having it there, myself. IMO, send a PR.

**Comment by RayfenWindspear** [comment]
I know what you mean, but when dealing with something such as a Set, which is _almost_ like a primitive type (like a slice), people can get into trouble if that becomes the bottleneck.

**Comment by sdboyer** [comment]
Oh, for sure. There's a reason I opened #26. I was mostly just being snarky-nitpicky about the way you set up your argument - sorry :)

So, let me be more clear - yes, I think there'd be value to this, specifically because it's trying to provide a primitive-ish datastructure. However, because the implementations here are based on the native map type, and the language [uses different impls for different key types](https://golang.org/src/runtime/hashmap.go), there's a limit on the information we can reasonably give. Separating the component that refers to the map's complexity contribution (as you originally did - perhaps in part because of this issue?), is a necessity.

**Comment by fatih** [comment]
To be honest, you both have valid points. But I'm rarely using this library myself too. This is a package from a time of me being a pre go programmer with limited experience.

Today I just would use a map with a concrete type or use one of the generators that would generate the code for me. I'm not removing the repo because there is still code outside that rely on this. So if you want performance or anything else, this is imho not the place :)

**Comment by RayfenWindspear** [comment]
I chatted with my old professor about sets in Go and he pointed out that given that sets can have varying contents and purposes, there isn't a straightforward all-case implementation. Which is why there isn't a set primitive type in Go. He also noted that instead of map[type]bool, it has become "popular" to use map[type]{}. He said using an empty struct requires no memory allocation. Allocating a slice of empty structs, say with make([]{},10) also allocates no memory... of course such a slice is useless, but it has other applications such as with channels.

As far as the code here goes, I haven't directly used it per se, but I have used the code as an example to build my own set code for my purposes. So it does have a place here on github, and I am grateful that you took the time to write it. If I get around to it, I may do my own Big-O analysis and submit a pull request. For now, I will close the issue and perhaps come back to it on my own time.

Thanks
